import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const demoProject = {
  id: 1, name: '软件工程课程大作业', project_type: '课程项目', description: '面向小组作业的智能协作与贡献管理', start_date: '2026-08-18', end_date: '2026-09-20',
  members: [
    { id: 1, name: '张三', role: 'owner', status: 'online', skills: ['后端', 'Python', '数据分析'], max_concurrent_tasks: 3 },
    { id: 2, name: '李四', role: 'member', status: 'busy', skills: ['前端', '交互设计'], max_concurrent_tasks: 3 },
    { id: 3, name: '王五', role: 'member', status: 'online', skills: ['数据库', '测试'], max_concurrent_tasks: 3 },
    { id: 4, name: '赵六', role: 'member', status: 'away', skills: ['产品', '文档'], max_concurrent_tasks: 2 },
  ],
  tasks: [
    { id: 101, title: '完成数据库设计', description: '确定实体关系、索引和初始化脚本', assignee_id: 3, assignee_name: '王五', status: 'in_progress', due_date: '2026-08-28', estimated_hours: 4, actual_hours: null, quality: null, task_type: '数据库' },
    { id: 102, title: '搭建前端页面骨架', description: '完成路由、布局与核心组件', assignee_id: 2, assignee_name: '李四', status: 'in_progress', due_date: '2026-08-29', estimated_hours: 8, actual_hours: 5.5, quality: null, task_type: '前端' },
    { id: 103, title: '撰写项目报告第三章', description: '整理系统设计和关键实现', assignee_id: 4, assignee_name: '赵六', status: 'assigned', due_date: '2026-08-31', estimated_hours: 5, actual_hours: null, quality: null, task_type: '文档' },
    { id: 104, title: '完成项目 PPT', description: '汇报结构、视觉规范和演示稿', assignee_id: null, assignee_name: null, status: 'unassigned', due_date: '2026-09-03', estimated_hours: 4, actual_hours: null, quality: null, task_type: '汇报' },
    { id: 105, title: '需求分析与用户访谈', description: '完成问卷、访谈并输出洞察', assignee_id: 1, assignee_name: '张三', status: 'completed', due_date: '2026-08-25', estimated_hours: 6, actual_hours: 5, quality: 4.5, task_type: '产品' },
    { id: 106, title: 'GitHub Actions 自动化', description: '配置测试与构建流水线', assignee_id: 1, assignee_name: '张三', status: 'overdue', due_date: '2026-08-22', estimated_hours: 3, actual_hours: null, quality: null, task_type: '后端' },
  ],
  contributions: [
    { id: 1, user_id: 1, user_name: '张三', kind: 'code', title: '提交 API 鉴权模块', description: '新增 6 个接口并补充单元测试', quantity: 8, created_at: '2026-08-23T09:20:00Z' },
    { id: 2, user_id: 2, user_name: '李四', kind: 'document', title: '更新交互流程图', description: '完成任务板和报告页的交互标注', quantity: 2, created_at: '2026-08-23T14:10:00Z' },
    { id: 3, user_id: 3, user_name: '王五', kind: 'code', title: '数据库索引优化', description: '添加 3 个复合索引，查询耗时下降 42%', quantity: 3, created_at: '2026-08-22T17:40:00Z' },
    { id: 4, user_id: 4, user_name: '赵六', kind: 'meeting', title: '主持周会并同步决策', description: '沉淀 4 条会议决策和行动项', quantity: 1, created_at: '2026-08-21T10:00:00Z' },
  ],
}

const statusMeta = {
  unassigned: { label: '未分配', tone: 'slate' }, assigned: { label: '待开始', tone: 'blue' }, in_progress: { label: '进行中', tone: 'amber' }, paused: { label: '已暂停', tone: 'purple' }, completed: { label: '已完成', tone: 'green' }, overdue: { label: '延期', tone: 'red' }, unfinished: { label: '未完成', tone: 'red' },
}
const nav = [{ id: 'overview', icon: '⌂', label: '项目总览' }, { id: 'tasks', icon: '✓', label: '任务看板' }, { id: 'contributions', icon: '◈', label: '贡献账本' }, { id: 'report', icon: '▥', label: '贡献报告' }, { id: 'agent', icon: '✦', label: '协作 Agent' }]
const avatarColors = ['#ffe4bd', '#d7e8ff', '#d9f3e3', '#eddcff', '#ffd9e0']

async function getJson(url) { const r = await fetch(url); if (!r.ok) throw new Error('network'); return r.json() }
async function sendJson(url, options = {}) { if (window.__collabDemoMode && url.includes('/agent')) throw new Error('demo-mode'); const r = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!r.ok) throw new Error('network'); return r.json() }
function initials(name = '') { return name.slice(0, 1) }
function formatDate(value) { if (!value) return '未设置'; const d = new Date(value); return `${d.getMonth() + 1}月${d.getDate()}日` }

function App() {
  const [project, setProject] = useState(demoProject)
  const [report, setReport] = useState(null)
  const [active, setActive] = useState('overview')
  const [loading, setLoading] = useState(true)
  const [online, setOnline] = useState(false)
  const [showTask, setShowTask] = useState(false)
  const [recommendTask, setRecommendTask] = useState(null)
  const [toast, setToast] = useState('')
  const [query, setQuery] = useState('')

  useEffect(() => { loadProject() }, [])
  useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 2600); return () => clearTimeout(t) } }, [toast])

  async function loadProject() {
    setLoading(true)
    try {
      const projects = await getJson('/api/projects')
      const id = projects[0]?.id
      if (!id) { window.__collabDemoMode = false; setProject(null); setReport(null); setOnline(true); return }
const [detail, rep, contributions] = await Promise.all([getJson(`/api/projects/${id}`), getJson(`/api/projects/${id}/report`), getJson(`/api/projects/${id}/contributions`)]); const names = Object.fromEntries((detail.members || []).map(m => [m.id, m.name])); detail.tasks = (detail.tasks || []).map(t => ({ ...t, assignee_name: names[t.assignee_id] || null })); window.__collabDemoMode = false; setProject({ ...detail, contributions }); setReport(rep); setOnline(true)
} catch { window.__collabDemoMode = true; setOnline(false); setProject(demoProject); setReport(null) } finally { setLoading(false) }
  }

  const tasks = project?.tasks || []
  const members = project?.members || []
  const activeTasks = tasks.filter(t => ['assigned', 'in_progress', 'paused'].includes(t.status))
  const completed = tasks.filter(t => t.status === 'completed').length
  const overdue = tasks.filter(t => ['overdue', 'unfinished'].includes(t.status)).length
  const progress = tasks.length ? Math.round(completed / tasks.length * 100) : 0
  const memberStats = useMemo(() => members.map(m => ({ ...m, current: tasks.filter(t => t.assignee_id === m.id && ['assigned', 'in_progress', 'paused'].includes(t.status)).length, done: tasks.filter(t => t.assignee_id === m.id && t.status === 'completed').length, quality: (() => { const q = tasks.filter(t => t.assignee_id === m.id && t.quality != null).map(t => t.quality); return q.length ? (q.reduce((a, b) => a + b, 0) / q.length).toFixed(1) : '—' })() })), [members, tasks])

  if (!loading && !project) return <CreateProjectView onCreated={async created => { const [detail, rep, contributions] = await Promise.all([getJson(`/api/projects/${created.id}`), getJson(`/api/projects/${created.id}/report`), getJson(`/api/projects/${created.id}/contributions`)]); const names = Object.fromEntries((detail.members || []).map(m => [m.id, m.name])); detail.tasks = (detail.tasks || []).map(t => ({ ...t, assignee_name: names[t.assignee_id] || null })); window.__collabDemoMode = false; setProject({ ...detail, contributions }); setReport(rep); setOnline(true) }} />

  async function taskAction(task, action) {
    try { const updated = await sendJson(`/api/tasks/${task.id}/${action}`, { method: 'POST' }); setProject(p => ({ ...p, tasks: p.tasks.map(t => t.id === task.id ? { ...t, ...updated } : t) })); setToast(`已将「${task.title}」标记为${statusMeta[updated.status]?.label || '已更新'}`) } catch { const next = { start: 'in_progress', pause: 'paused', resume: 'in_progress', complete: 'completed', overdue: 'overdue', unfinished: 'unfinished' }[action]; setProject(p => ({ ...p, tasks: p.tasks.map(t => t.id === task.id ? { ...t, status: next } : t) })); setToast('演示模式：状态已更新') }
  }

  async function createTask(data) {
    try { const t = await sendJson(`/api/projects/${project.id}/tasks`, { method: 'POST', body: JSON.stringify(data) }); setProject(p => ({ ...p, tasks: [t, ...p.tasks] })); setToast('任务已创建') } catch { const t = { ...data, id: Date.now(), status: data.assignee_id ? 'assigned' : 'unassigned', assignee_name: members.find(m => m.id === Number(data.assignee_id))?.name || null }; setProject(p => ({ ...p, tasks: [t, ...p.tasks] })); setToast('演示模式：任务已创建') }
    setShowTask(false)
  }

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">▦</div><div><div className="brand-name">协作账本</div><div className="brand-sub">COLLAB LEDGER</div></div></div>
      <div className="workspace-label">我的工作区</div>
      <div className="project-switch"><div className="project-dot"/><div><strong>{project.name}</strong><span>{project.project_type || '项目空间'}</span></div><span className="chevron">⌄</span></div>
      <nav>{nav.map(item => <button key={item.id} className={`nav-item ${active === item.id ? 'selected' : ''}`} onClick={() => setActive(item.id)}><span className="nav-icon">{item.icon}</span>{item.label}{item.id === 'tasks' && overdue > 0 && <span className="nav-badge">{overdue}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="privacy-card"><span className="privacy-icon">◉</span><div><strong>隐私友好设计</strong><p>只记录协作成果，不监控个人设备。</p></div></div><div className="profile-chip"><div className="avatar avatar-me">张</div><div><strong>张三</strong><span>项目负责人</span></div><span className="more">•••</span></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="breadcrumb"><span>项目空间</span><b>/</b><strong>{nav.find(n => n.id === active)?.label}</strong></div><div className="top-actions"><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索任务、成员…"/></div><button className="icon-button" title="通知">♢<i/></button><button className="help-button">?</button></div></header>
      <div className="page-wrap">
        {loading ? <div className="loading-state">正在加载项目空间…</div> : <>
          {active === 'overview' && <Overview project={project} memberStats={memberStats} tasks={tasks} progress={progress} completed={completed} overdue={overdue} activeTasks={activeTasks} online={online} onNavigate={setActive} onAction={taskAction} onRecommend={setRecommendTask}/>} 
          {active === 'tasks' && <TasksView tasks={tasks.filter(t => !query || `${t.title}${t.assignee_name || ''}`.includes(query))} members={members} onAction={taskAction} onCreate={() => setShowTask(true)} onRecommend={setRecommendTask}/>} 
          {active === 'contributions' && <ContributionsView project={project} members={members} online={online} setProject={setProject} onToast={setToast}/>} 
          {active === 'report' && <ReportView project={project} report={report} memberStats={memberStats} tasks={tasks}/>} 
          {active === 'agent' && <AgentView project={project} online={online} onRecommend={setRecommendTask}/>} 
        </>}
      </div>
    </main>
    {showTask && <TaskModal members={members} onClose={() => setShowTask(false)} onSave={createTask}/>} 
    {recommendTask && <RecommendModal task={recommendTask} project={project} members={members} onClose={() => setRecommendTask(null)} onToast={setToast} setProject={setProject}/>} 
    {toast && <div className="toast">✓ {toast}</div>}
  </div>
}

function PageTitle({ eyebrow, title, desc, action }) { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{desc && <p>{desc}</p>}</div>{action}</div> }
function Overview({ project, memberStats, tasks, progress, completed, overdue, activeTasks, online, onNavigate, onAction, onRecommend }) {
  return <><PageTitle eyebrow="周一 · 8月24日" title="早上好，张三 👋" desc="这是你们小组本周的协作脉搏。" action={<button className="primary-button" onClick={() => onNavigate('tasks')}><span>＋</span> 新建任务</button>}/>
    <div className="overview-grid"><section className="hero-card"><div className="hero-copy"><span className="live-pill"><i/> 项目进行中</span><h2>{project.name}</h2><p>{project.description || '让每一份协作成果都被看见。'}</p><div className="hero-meta"><span>◷ {formatDate(project.start_date)} — {formatDate(project.end_date)}</span><span>♧ {memberStats.length} 位成员</span></div></div><div className="progress-ring" style={{ '--progress': `${progress * 3.6}deg` }}><div><strong>{progress}%</strong><span>项目进度</span></div></div></section>
      <div className="metric-row"><Metric label="进行中任务" value={activeTasks.length} hint="较上周 +2" trend="up" color="amber"/><Metric label="已完成" value={completed} hint={`共 ${tasks.length} 项任务`} trend="neutral" color="green"/><Metric label="需要关注" value={overdue} hint="建议今天处理" trend="down" color="red"/></div>
    </div>
    <div className="section-heading"><div><h2>协作状态</h2><p>成员主动同步的工作状态</p></div><button className="text-button" onClick={() => onNavigate('contributions')}>查看贡献账本 →</button></div>
    <div className="member-grid">{memberStats.map((m, i) => <MemberCard key={m.id} member={m} index={i}/>)}</div>
    <div className="dashboard-columns"><section className="panel task-panel"><div className="panel-header"><div><h2>需要你关注的任务</h2><p>按优先级和截止时间排序</p></div><button className="text-button" onClick={() => onNavigate('tasks')}>查看全部 →</button></div><div className="task-list">{tasks.filter(t => t.status !== 'completed').slice(0, 4).map(t => <TaskRow key={t.id} task={t} onAction={onAction} onRecommend={onRecommend}/>)}</div></section><section className="panel insight-panel"><div className="panel-header"><div><h2>本周协作洞察</h2><p>基于已有事实生成的提示</p></div><span className="sparkle">✦</span></div><div className="insight-main"><div className="insight-icon">↗</div><div><strong>任务节奏不错</strong><p>小组平均完成效率比预估快 <b>18%</b>，继续保持！</p></div></div><div className="insight-line"><span>风险提示</span><strong>{overdue ? `有 ${overdue} 项任务已延期` : '暂无延期任务'}</strong><button onClick={() => onNavigate('agent')}>让 Agent 分析</button></div><div className="activity-mini"><span className="activity-dot green"/><span>最近一次活动</span><strong>{online ? '数据已与 API 同步' : '当前使用演示数据'}</strong></div></section></div>
  </>
}
function Metric({ label, value, hint, trend, color }) { return <div className={`metric-card ${color}`}><div className="metric-top"><span>{label}</span><span className={`trend ${trend}`}>{trend === 'up' ? '↗' : trend === 'down' ? '↘' : '—'}</span></div><strong>{value}</strong><small>{hint}</small></div> }
function MemberCard({ member, index }) { const status = { online: ['协作中', 'online'], busy: ['专注中', 'busy'], away: ['暂离', 'away'], offline: ['离线', 'offline'] }[member.status] || ['协作中', 'online']; return <div className="member-card"><div className="member-head"><div className={`avatar avatar-${index % avatarColors.length}`} style={{ background: avatarColors[index % avatarColors.length] }}>{initials(member.name)}</div><div><strong>{member.name}</strong><span className={`status ${status[1]}`}><i/>{status[0]}</span></div><button className="kebab">•••</button></div><div className="member-skills">{(member.skills || []).slice(0, 3).map(s => <span key={s}>{s}</span>)}</div><div className="member-foot"><span>当前任务 <b>{member.current}/{member.max_concurrent_tasks}</b></span><span>本周完成 <b>{member.done}</b></span></div><div className="load-bar"><i style={{ width: `${Math.min(100, member.current / member.max_concurrent_tasks * 100)}%` }}/></div></div> }
function TaskRow({ task, onAction, onRecommend }) { const meta = statusMeta[task.status] || statusMeta.unassigned; const action = task.status === 'in_progress' ? 'complete' : task.status === 'paused' ? 'resume' : task.status === 'assigned' ? 'start' : null; return <div className="task-row"><div className={`priority-dot ${meta.tone}`}/><div className="task-row-main"><strong>{task.title}</strong><div className="task-row-meta"><span className={`tag ${meta.tone}`}>{meta.label}</span><span>截止 {formatDate(task.due_date)}</span>{task.assignee_name ? <span className="assignee-inline"><span className="tiny-avatar">{initials(task.assignee_name)}</span>{task.assignee_name}</span> : <button className="assign-link" onClick={() => onRecommend(task)}>＋ 分配负责人</button>}</div></div>{action && <button className="row-action" onClick={() => onAction(task, action)}>{action === 'complete' ? '完成' : action === 'resume' ? '继续' : '开始'}</button>}<button className="row-more">···</button></div> }

function TasksView({ tasks, members, onAction, onCreate, onRecommend }) { const [filter, setFilter] = useState('all'); const filtered = filter === 'all' ? tasks : tasks.filter(t => t.status === filter); const columns = ['unassigned', 'assigned', 'in_progress', 'paused', 'completed', 'overdue', 'unfinished']; return <><PageTitle eyebrow="TASK BOARD" title="任务看板" desc="从开始到完成，记录每一段真实的协作过程。" action={<button className="primary-button" onClick={onCreate}>＋ 新建任务</button>}/><div className="board-toolbar"><div className="filter-tabs">{[['all', '全部'], ['in_progress', '进行中'], ['unassigned', '待分配'], ['completed', '已完成'], ['overdue', '延期']].map(([id, label]) => <button className={filter === id ? 'active' : ''} key={id} onClick={() => setFilter(id)}>{label}<span>{id === 'all' ? tasks.length : tasks.filter(t => t.status === id).length}</span></button>)}</div><div className="board-actions"><button className="ghost-button">≡ 筛选</button><button className="ghost-button">↕ 排序</button></div></div><div className="board-grid">{columns.map(status => { const list = filtered.filter(t => t.status === status); const m = statusMeta[status]; return <div className="board-column" key={status}><div className="column-header"><span className={`column-dot ${m.tone}`}/><strong>{m.label}</strong><span className="column-count">{list.length}</span><button>＋</button></div><div className="column-cards">{list.map(t => <TaskCard key={t.id} task={t} members={members} onAction={onAction} onRecommend={onRecommend}/>)}{!list.length && <div className="empty-column">暂无任务</div>}</div></div> })}</div></> }
function TaskCard({ task, onAction, onRecommend }) { const m = statusMeta[task.status]; const action = task.status === 'in_progress' ? 'complete' : task.status === 'assigned' ? 'start' : task.status === 'paused' ? 'resume' : null; return <article className="task-card"><div className="task-card-top"><span className={`tag ${m.tone}`}>{m.label}</span><button className="kebab">•••</button></div><h3>{task.title}</h3>{task.description && <p>{task.description}</p>}<div className="task-card-info"><span>◷ {formatDate(task.due_date)}</span><span>◒ {task.estimated_hours || '—'}h</span></div><div className="task-card-bottom">{task.assignee_name ? <span className="assignee-inline"><span className="tiny-avatar">{initials(task.assignee_name)}</span>{task.assignee_name}</span> : <button className="assign-link" onClick={() => onRecommend(task)}>＋ 分配负责人</button>}{action && <button className="mini-action" onClick={() => onAction(task, action)}>{action === 'complete' ? '完成任务' : action === 'resume' ? '继续' : '开始'}</button>}</div></article> }

function ContributionsView({ project, members, online, setProject, onToast }) { const [kind, setKind] = useState('all'); const [open, setOpen] = useState(false); const contributions = project.contributions || []; const list = kind === 'all' ? contributions : contributions.filter(c => c.kind === kind); async function save(data) { try { const c = await sendJson(`/api/projects/${project.id}/contributions`, { method: 'POST', body: JSON.stringify(data) }); setProject(p => ({ ...p, contributions: [c, ...(p.contributions || [])] })); onToast('贡献记录已保存') } catch { const m = members.find(x => x.id === Number(data.user_id)); setProject(p => ({ ...p, contributions: [{ ...data, id: Date.now(), user_name: m?.name || '我', created_at: new Date().toISOString() }, ...(p.contributions || [])] })); onToast('演示模式：贡献记录已保存') } setOpen(false) } return <><PageTitle eyebrow="CONTRIBUTION LEDGER" title="贡献账本" desc="记录做了什么，而不是监控正在做什么。" action={<button className="primary-button" onClick={() => setOpen(true)}>＋ 记录贡献</button>}/><div className="privacy-banner"><span>◉</span><div><strong>这是一个公平秤，不是监控器</strong><p>成员只会被记录项目相关的产出：任务、代码、文档和会议。数据默认仅对项目组可见。</p></div><span className="sync-state">{online ? '● 已同步' : '◌ 演示数据'}</span></div><div className="ledger-summary"><Metric label="本周贡献" value={contributions.length} hint="条可追溯记录" trend="up" color="blue"/><Metric label="代码提交" value={contributions.filter(c => c.kind === 'code').reduce((a, c) => a + (c.quantity || 1), 0)} hint="次 commit / 变更" trend="up" color="purple"/><Metric label="活跃成员" value={new Set(contributions.map(c => c.user_id)).size} hint={`共 ${members.length} 位成员`} trend="neutral" color="green"/></div><div className="ledger-panel panel"><div className="ledger-header"><div className="filter-tabs compact">{[['all', '全部'], ['code', '代码'], ['document', '文档'], ['meeting', '会议'], ['task', '任务']].map(([id, label]) => <button key={id} className={kind === id ? 'active' : ''} onClick={() => setKind(id)}>{label}</button>)}</div><span className="ledger-note">按时间倒序</span></div><div className="ledger-list">{list.map((c, i) => <ContributionItem key={c.id} c={c} i={i}/>)}{!list.length && <div className="empty-state">还没有这类贡献记录</div>}</div></div>{open && <ContributionModal members={members} onClose={() => setOpen(false)} onSave={save}/>}</> }
function ContributionItem({ c, i }) { const icons = { code: ['⌘', 'purple'], document: ['▤', 'blue'], meeting: ['◉', 'amber'], task: ['✓', 'green'], other: ['✦', 'slate'] }; const [icon, tone] = icons[c.kind] || icons.other; return <div className="contribution-item"><div className={`contribution-icon ${tone}`}>{icon}</div><div className="contribution-main"><strong>{c.title || '未命名贡献'}</strong><p>{c.description || '成员提交了一条项目产出记录'}</p><span>{c.user_name} · {formatDate(c.created_at)}</span></div><div className="contribution-qty"><strong>{c.quantity || 1}</strong><span>{c.kind === 'code' ? '次' : '项'}</span></div></div> }

function ReportView({ project, report, memberStats, tasks }) { const rows = report?.members || memberStats.map(m => ({ user_id: m.id, name: m.name, tasks_total: tasks.filter(t => t.assignee_id === m.id).length, tasks_completed: m.done, tasks_overdue: tasks.filter(t => t.assignee_id === m.id && ['overdue', 'unfinished'].includes(t.status)).length, average_quality: m.quality === '—' ? null : Number(m.quality), actual_hours: tasks.filter(t => t.assignee_id === m.id).reduce((a, t) => a + (t.actual_hours || 0), 0) })); const total = report?.overall?.tasks || tasks.length; const done = report?.overall?.completed || tasks.filter(t => t.status === 'completed').length; return <><PageTitle eyebrow="PROJECT REPORT" title="项目贡献报告" desc="用事实回顾协作过程，为组内互评提供依据。" action={<button className="ghost-button">⇩ 导出报告</button>}/><div className="report-highlight"><div><span className="eyebrow">PROJECT PULSE</span><h2>小组整体进度</h2><p>截至今天，项目已完成 {done} / {total} 项任务。</p></div><div className="big-progress"><strong>{total ? Math.round(done / total * 100) : 0}%</strong><div><div className="progress-track"><i style={{ width: `${total ? done / total * 100 : 0}%` }}/></div><span>整体完成度</span></div></div></div><div className="report-grid"><section className="panel"><div className="panel-header"><div><h2>成员贡献概览</h2><p>不形成公开排名，仅用于项目复盘</p></div><span className="sparkle">✦</span></div><div className="report-table"><div className="report-row report-head"><span>成员</span><span>完成任务</span><span>延期</span><span>平均质量</span><span>实际耗时</span></div>{rows.map(r => <div className="report-row" key={r.user_id}><span className="assignee-inline"><span className="tiny-avatar">{initials(r.name)}</span><strong>{r.name}</strong></span><span>{r.tasks_completed} / {r.tasks_total}</span><span className={r.tasks_overdue ? 'danger-text' : ''}>{r.tasks_overdue}</span><span>{r.average_quality ? <><b>{r.average_quality}</b><small> / 5</small></> : '—'}</span><span>{r.actual_hours || 0}h</span></div>)}</div></section><section className="panel report-insight"><div className="panel-header"><div><h2>协作画像摘要</h2><p>来自多次项目的长期积累</p></div></div><div className="profile-insight"><div className="profile-large">张</div><div><strong>张三</strong><p>主要承担后端开发与数据处理工作，在代码任务方面完成速度较快，同时承担了较多核心任务。</p></div></div><div className="skill-bars"><SkillBar label="后端 / Python" value={88} color="purple"/><SkillBar label="数据分析" value={74} color="blue"/><SkillBar label="产品协作" value={52} color="amber"/></div></section></div></> }
function SkillBar({ label, value, color }) { return <div className="skill-bar"><div><span>{label}</span><b>{value}%</b></div><div className="progress-track"><i className={color} style={{ width: `${value}%` }}/></div></div> }

function AgentView({ project, online, onRecommend }) { const [messages, setMessages] = useState([{ role: 'agent', text: '你好，我是协作 Agent。可以帮你分析项目风险、生成周报，或推荐任务负责人。' }]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); async function ask(text = input) { if (!text.trim() || busy) return; setMessages(m => [...m, { role: 'user', text }]); setInput(''); setBusy(true); try { const r = await sendJson(`/api/projects/${project.id}/agent`, { method: 'POST', body: JSON.stringify({ message: text }) }); setMessages(m => [...m, { role: 'agent', text: r.answer }]) } catch { const fallback = text.includes('风险') || text.includes('延期') ? '目前最大的风险是「GitHub Actions 自动化」已经延期，建议今天由张三优先处理，或拆分给其他成员。' : text.includes('周报') || text.includes('总结') ? '本周共完成 1 项任务，4 位成员产生了 4 条贡献记录。整体进度正常，建议关注 1 项延期任务。' : '我可以帮助分析项目风险、生成周报或推荐任务负责人。试试问我“目前项目最大的风险是什么？”'; setMessages(m => [...m, { role: 'agent', text: fallback }]) } finally { setBusy(false) } } return <><PageTitle eyebrow="COLLAB AGENT" title="协作 Agent" desc="把项目事实变成可执行的下一步建议。" action={<span className={`api-pill ${online ? 'connected' : ''}`}><i/> {online ? 'API 已连接' : '演示模式'}</span>}/><div className="agent-layout"><section className="agent-chat panel"><div className="agent-chat-head"><div className="agent-face">✦</div><div><strong>协作 Agent</strong><span>基于项目事实回答，不替你做最终判断</span></div><span className="agent-online"><i/> 在线</span></div><div className="messages">{messages.map((m, i) => <div key={i} className={`message ${m.role}`}><div className="message-avatar">{m.role === 'agent' ? '✦' : '张'}</div><div className="message-bubble">{m.text}</div></div>)}{busy && <div className="message agent"><div className="message-avatar">✦</div><div className="message-bubble typing"><i/><i/><i/></div></div>}</div><div className="suggestions"><button onClick={() => ask('目前项目最大的风险是什么？')}>⌁ 目前项目最大的风险是什么？</button><button onClick={() => ask('帮我总结一下这周我们组的工作')}>◷ 总结本周工作</button><button onClick={() => onRecommend({ id: 0, title: '完成项目 PPT', task_type: '汇报', estimated_hours: 4 })}>✦ 谁适合完成项目 PPT？</button></div><div className="agent-input"><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && ask()} placeholder="输入你想了解的项目问题…"/><button onClick={() => ask()}>发送 ↑</button></div></section><aside className="agent-side"><div className="panel"><div className="panel-header"><div><h2>可询问 Agent</h2><p>试试这些问题</p></div></div><div className="question-list"><button onClick={() => ask('目前项目最大的风险是什么？')}>目前项目最大的风险是什么？<span>→</span></button><button onClick={() => ask('帮我总结一下这周我们组的工作')}>帮我总结一下这周我们组的工作<span>→</span></button><button onClick={() => onRecommend({ id: 0, title: '完成项目 PPT', task_type: '汇报', estimated_hours: 4 })}>这个任务应该给谁？<span>→</span></button></div></div><div className="agent-note"><span>◎</span><div><strong>AI 只提供建议</strong><p>推荐基于成员主动提供的技能、任务历史和当前负载。最终决定权始终在组长和成员手中。</p></div></div></aside></div></> }

function TaskModal({ members, onClose, onSave }) { const [form, setForm] = useState({ title: '', description: '', task_type: '其他', estimated_hours: 4, due_date: '', assignee_id: '' }); const update = (k, v) => setForm(f => ({ ...f, [k]: v })); return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">NEW TASK</span><h2>创建新任务</h2></div><button onClick={onClose}>×</button></div><label>任务名称<input autoFocus value={form.title} onChange={e => update('title', e.target.value)} placeholder="例如：完成项目 PPT"/></label><label>任务描述<textarea value={form.description} onChange={e => update('description', e.target.value)} placeholder="补充任务背景和交付标准…"/></label><div className="form-row"><label>任务类型<select value={form.task_type} onChange={e => update('task_type', e.target.value)}><option>其他</option><option>前端</option><option>后端</option><option>数据库</option><option>文档</option><option>汇报</option></select></label><label>预计耗时（小时）<input type="number" min="0" value={form.estimated_hours} onChange={e => update('estimated_hours', Number(e.target.value))}/></label></div><div className="form-row"><label>截止日期<input type="date" value={form.due_date} onChange={e => update('due_date', e.target.value)}/></label><label>负责人（可稍后分配）<select value={form.assignee_id} onChange={e => update('assignee_id', e.target.value)}><option value="">暂不分配</option>{members.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label></div><div className="modal-actions"><button className="ghost-button" onClick={onClose}>取消</button><button className="primary-button" disabled={!form.title.trim()} onClick={() => onSave({ ...form, assignee_id: form.assignee_id ? Number(form.assignee_id) : null, estimated_hours: Number(form.estimated_hours) })}>创建任务</button></div></div></div> }
function ContributionModal({ members, onClose, onSave }) { const [form, setForm] = useState({ user_id: members[0]?.id || '', kind: 'code', title: '', description: '', quantity: 1 }); return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">LOG CONTRIBUTION</span><h2>记录一条贡献</h2></div><button onClick={onClose}>×</button></div><div className="form-row"><label>成员<select value={form.user_id} onChange={e => setForm(f => ({ ...f, user_id: Number(e.target.value) }))}>{members.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>贡献类型<select value={form.kind} onChange={e => setForm(f => ({ ...f, kind: e.target.value }))}><option value="code">代码 / Commit</option><option value="document">文档</option><option value="meeting">会议</option><option value="task">任务</option><option value="other">其他</option></select></label></div><label>贡献标题<input autoFocus value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} placeholder="例如：完成 API 鉴权模块"/></label><label>补充说明<textarea value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} placeholder="写下可被复盘的事实…"/></label><label>数量 / 次数<input type="number" min="1" value={form.quantity} onChange={e => setForm(f => ({ ...f, quantity: Number(e.target.value) }))}/></label><div className="modal-actions"><button className="ghost-button" onClick={onClose}>取消</button><button className="primary-button" disabled={!form.title.trim()} onClick={() => onSave(form)}>保存记录</button></div></div></div> }

    function RecommendModal({ task, project, members, onClose, onToast, setProject }) { const [results, setResults] = useState([]); const [busy, setBusy] = useState(true); useEffect(() => { (async () => { try { const q = new URLSearchParams({ task_name: task.title, task_type: task.task_type || '', estimated_hours: task.estimated_hours || 1 }); const r = await getJson(`/api/projects/${project.id}/recommendations?${q}`); setResults(r.recommendations || []) } catch { const scores = members.map((m, i) => ({ user_id: m.id, name: m.name, score: Math.max(62, 92 - i * 8), reasons: { skills: m.skills, average_quality: i === 0 ? 4.7 : 4.2, efficiency: i === 0 ? 1.12 : 1.02, current_load: `${i % 3}/3` } })).sort((a, b) => b.score - a.score); setResults(scores) } finally { setBusy(false) } })() }, []); async function choose(r) { if (task.id) { try { const updated = await sendJson(`/api/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ assignee_id: r.user_id, status: 'assigned' }) }); setProject(p => ({ ...p, tasks: p.tasks.map(t => t.id === task.id ? { ...t, ...updated, assignee_name: r.name } : t) })) } catch { setProject(p => ({ ...p, tasks: p.tasks.map(t => t.id === task.id ? { ...t, assignee_id: r.user_id, assignee_name: r.name, status: 'assigned' } : t) })) } } onToast(`已将「${task.title}」分配给${r.name}`); onClose() } return <div className="modal-backdrop"><div className="modal recommend-modal"><div className="modal-head"><div><span className="eyebrow">AI RECOMMENDATION</span><h2>谁适合负责这个任务？</h2><p className="modal-sub">「{task.title}」 · 基于技能、质量、效率和当前负载</p></div><button onClick={onClose}>×</button></div>{busy ? <div className="recommend-loading"><span className="loader"/>正在计算匹配度…</div> : <div className="recommend-list">{results.map((r, i) => <div className={`recommend-item ${i === 0 ? 'best' : ''}`} key={r.user_id}><div className="rank">{i + 1}</div><div className={`avatar avatar-${i % 5}`}>{initials(r.name)}</div><div className="recommend-main"><div className="recommend-name"><strong>{r.name}</strong>{i === 0 && <span className="best-label">最佳匹配</span>}<span className="score">{Math.round(r.score)}<small>%</small></span></div><div className="reason-chips">{(r.reasons?.skills || []).slice(0, 2).map(s => <span key={s}>⌁ {s}</span>)}<span>质量 {r.reasons?.average_quality || '—'}/5</span><span>负载 {r.reasons?.current_load || '—'}</span></div><div className="match-track"><i style={{ width: `${r.score}%` }}/></div></div><button className="choose-button" onClick={() => choose(r)}>采纳</button></div>)}</div>}<div className="recommend-foot"><span>◉ 推荐仅供参考，不会自动替你做决定。</span><button className="ghost-button" onClick={onClose}>手动指定</button></div></div></div> }

function CreateProjectView({ onCreated }) {
  const [form, setForm] = useState({ name: '', project_type: '课程项目', description: '', start_date: '', end_date: '', owner_name: '', owner_email: '', skills: '' })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }))
  async function submit(event) {
    event.preventDefault(); setError('')
    if (!form.name.trim() || !form.owner_name.trim()) { setError('请填写项目名称和负责人姓名'); return }
    setBusy(true)
    try {
      const owner = await sendJson('/api/users', { method: 'POST', body: JSON.stringify({ name: form.owner_name.trim(), email: form.owner_email.trim() || null, skills: form.skills.split(/[,，]/).map(s => s.trim()).filter(Boolean), status: 'online' }) })
      const project = await sendJson('/api/projects', { method: 'POST', body: JSON.stringify({ name: form.name.trim(), project_type: form.project_type, description: form.description.trim() || null, start_date: form.start_date || null, end_date: form.end_date || null, owner_id: owner.id }) })
      await onCreated(project)
    } catch (err) { setError('创建失败，请确认后端已启动，并检查项目名称和负责人信息。') } finally { setBusy(false) }
  }
  return <div className="create-project-screen"><div className="create-project-card"><div className="brand create-brand"><div className="brand-mark">▦</div><div><div className="brand-name">协作账本</div><div className="brand-sub">COLLAB LEDGER</div></div></div><div className="eyebrow">FIRST PROJECT</div><h1>创建你的第一个项目</h1><p className="create-project-desc">项目数据会写入 SQLite，之后任务、贡献和 Agent 记忆都会归属于这个真实项目。</p><form onSubmit={submit}><div className="form-row"><label>项目名称<input autoFocus value={form.name} onChange={e => update('name', e.target.value)} placeholder="例如：软件工程课程大作业" /></label><label>项目类型<select value={form.project_type} onChange={e => update('project_type', e.target.value)}><option>课程项目</option><option>竞赛项目</option><option>科研项目</option><option>其他</option></select></label></div><label>项目简介<textarea value={form.description} onChange={e => update('description', e.target.value)} placeholder="说明项目目标和协作范围…" /></label><div className="form-row"><label>开始日期<input type="date" value={form.start_date} onChange={e => update('start_date', e.target.value)} /></label><label>结束日期<input type="date" value={form.end_date} onChange={e => update('end_date', e.target.value)} /></label></div><div className="form-section-title">创建者 / 组长</div><div className="form-row"><label>姓名<input value={form.owner_name} onChange={e => update('owner_name', e.target.value)} placeholder="例如：张三" /></label><label>邮箱（可选）<input value={form.owner_email} onChange={e => update('owner_email', e.target.value)} placeholder="name@example.com" /></label></div><label>擅长领域（逗号分隔）<input value={form.skills} onChange={e => update('skills', e.target.value)} placeholder="Python，后端，数据分析" /></label>{error && <div className="form-error">{error}</div>}<button className="primary-button create-submit" disabled={busy}>{busy ? '正在创建…' : '创建项目并进入工作台 →'}</button></form><div className="create-privacy">◉ 只记录项目协作成果，不采集私人聊天、桌面、摄像头或键鼠数据。</div></div></div>
}

class AppErrorBoundary extends React.Component {
  constructor(props) { super(props); this.state = { error: null } }
  static getDerivedStateFromError(error) { return { error } }
  componentDidCatch(error, info) { console.error('协作账本前端运行时错误', error, info) }
  render() {
    if (this.state.error) return <div className="app-error-screen"><div><div className="brand-mark">!</div><h1>页面加载遇到问题</h1><p>{this.state.error.message || '未知前端错误'}</p><button className="primary-button" onClick={() => window.location.reload()}>重新加载</button></div></div>
    return this.props.children
  }
}

const root = createRoot(document.getElementById('root')); root.render(<AppErrorBoundary><App /></AppErrorBoundary>)

